INCLUDE(LibFindMacros)

# Find the include directories
FIND_PATH(POPT_INCLUDE_DIR
    NAMES popt.h
    HINTS ${POPT_PREFIX}/include
    )

FIND_LIBRARY(POPT_LIBRARY
    NAMES popt
    HINTS ${POPT_PREFIX}/lib
    )

SET(POPT_PROCESS_INCLUDES POPT_INCLUDE_DIR)
SET(POPT_PROCESS_LIBS POPT_LIBRARY)

LIBFIND_PROCESS(POPT)

